# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

# Setup
title: Elixir School
description:
  en: Lessons about the Elixir programming language
  jp: プログラミング言語Elixirのレッスン
  cn: Elixir 编程语言教程
  es: Lecciones acerca del lenguaje de programación Elixir
  pt: Lições sobre a linguagem de programação Elixir
  vi: Giáo trình cho ngôn ngữ lập trình Elixir
  ru: Уроки программирования на языке Elixir
  sk: Lekcie o programovacom jazyku Elixir
  fr: Leçons sur le langage de programmation Elixir
  gr: Μαθήματα προγραμματισμού της γλώσσας Elixir
  it: Lezioni sul linguaggio di programmazione Elixir
  pl: Lekcje programowania w języku Elixir
  my: Pelajaran mengenai bahasa aturcara Elixir
baseurl: /
url: http://localhost:4000
og_image: https://elixirschool.com/assets/fb_share.jpg
permalink: pretty
languages: ['en', 'jp', 'cn', 'es', 'pt', 'vi', 'ru', 'sk', 'fr', 'gr', 'it', 'pl', 'my']
default_lang: en
exclude_from_localization: []
sections:
  - tag: basics
    label:
      en: Basics
      jp: 基礎
      cn: 基础
      es: Básico
      pt: Básico
      vi: Cơ bản
      ru: Основы
      my: Asas
      sk: Základy
      fr: Bases
      gr: Βασικά
      it: Base
      pl: Podstawy
  - tag: advanced
    label:
      en: Advanced
      jp: 上級
      cn: 高级
      es: Avanzado
      pt: Avançado
      vi: Nâng cao
      ru: Продвинутый
      my: Lanjutan
      sk: Pokročilé
      fr: Avancé
      gr: Προχωρημένα
      it: Avanzato
      pl: Zaawansowane
  - tag: specifics
    label:
      en: Specifics
      jp: 詳細
      cn: 详情
      es: Específico
      pt: Específico
      vi: Cụ thể
      ru: Специфика
      my: Khusus
      sk: Špecifiká
      fr: Spécificités
      gr: Ιδιαιτερότητες
      it: Specifiche
      pl: Specyficzne

gems:
  - kramdown
  - jekyll-assets
  - jekyll-sitemap

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
assets:
  compress:
    css: sass
    js:  uglifier

sitemap:
  file: '/sitemap.xml'
  include_posts:
      - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'
