source 'https://rubygems.org'
ruby '2.3.0'

gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', :require => 'spec'
gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'puma'
gem 'rack-jekyll'
gem 'rake'
gem 'sprockets-es6'
